import type {
  MockDb,
  ProjectRow,
  SchemeRow,
  SchemeLineRow,
} from './types'
import { MOCK_USER_ID } from './types'

const baseDate = '2026-04-20T10:00:00.000Z'

function project(
  id: string,
  name: string,
  customer: string | null,
  offsetMinutes: number,
): ProjectRow {
  const ts = new Date(new Date(baseDate).getTime() + offsetMinutes * 60_000).toISOString()
  return {
    id,
    name,
    customer,
    user_id: MOCK_USER_ID,
    created_at: ts,
    updated_at: ts,
  }
}

function scheme(
  id: string,
  projectId: string,
  device_name: string,
  installation_location: string | null,
  phases_count: 1 | 3,
  partial: Partial<SchemeRow>,
  offsetMinutes: number,
): SchemeRow {
  const ts = new Date(new Date(baseDate).getTime() + offsetMinutes * 60_000).toISOString()
  return {
    id,
    project_id: projectId,
    device_name,
    shell_brand: null,
    shell_code: null,
    installation_method: null,
    protection_degree: null,
    installation_location,
    phases_count,
    network_type: null,
    power_supply_from: null,
    modules_count: null,
    input_device_type: null,
    nominal_current: null,
    trip_setting: null,
    switching_capacity: null,
    protection_characteristic: null,
    poles_count: null,
    differential_current: null,
    designation: null,
    cable_info: null,
    installed_power_kva: null,
    installed_power_current: null,
    calculated_power_kva: null,
    calculated_current: null,
    demand_coefficient: 1,
    current_phase_a: null,
    current_phase_b: null,
    current_phase_c: null,
    created_at: ts,
    updated_at: ts,
    ...partial,
  }
}

function line(
  id: string,
  schemeId: string,
  line_order: number,
  partial: Partial<SchemeLineRow>,
): SchemeLineRow {
  return {
    id,
    scheme_id: schemeId,
    line_order,
    circuit_breaker_designation: null,
    circuit_breaker_type: null,
    cb_nominal_current: null,
    cb_trip_setting: null,
    cb_protection_type: null,
    cb_differential_current: null,
    cable_designation: null,
    cable_brand: null,
    cable_length: null,
    pipe_designation: null,
    pipe_length: null,
    pipe_marking: null,
    power_kw: null,
    phase_a_current: null,
    phase_b_current: null,
    phase_c_current: null,
    cos_phi: null,
    load_name: null,
    load_type: null,
    load_drawing: null,
    created_at: baseDate,
    updated_at: baseDate,
    ...partial,
  }
}

const PROJECT_1 = '11111111-1111-1111-1111-111111111111'
const PROJECT_2 = '22222222-2222-2222-2222-222222222222'
const PROJECT_3 = '33333333-3333-3333-3333-333333333333'

const SCHEME_1A = 'aaaaaaa1-1111-4111-8111-111111111111'
const SCHEME_1B = 'aaaaaaa2-1111-4111-8111-111111111111'
const SCHEME_2A = 'aaaaaaa3-2222-4222-8222-222222222222'

export function createDefaultData(): MockDb {
  const projects: ProjectRow[] = [
    project(PROJECT_1, 'Офис на Тверской', 'ООО «Ромашка»', 30),
    project(PROJECT_2, 'Магазин на Невском', 'ИП Иванов', 20),
    project(PROJECT_3, 'Склад в Подольске', null, 10),
  ]

  const schemes: SchemeRow[] = [
    scheme(
      SCHEME_1A,
      PROJECT_1,
      'ЩС-1 Освещение',
      'Этаж 1, коридор',
      1,
      {
        shell_brand: 'ABB',
        shell_code: 'AT52',
        installation_method: 'Встраиваемый',
        protection_degree: 'IP30',
        network_type: 'TN-S',
        power_supply_from: 'ВРУ-1',
        modules_count: 24,
        input_device_type: 'Автомат',
        nominal_current: 25,
        trip_setting: 25,
        protection_characteristic: 'C',
        poles_count: 2,
        designation: 'QF1',
      },
      31,
    ),
    scheme(
      SCHEME_1B,
      PROJECT_1,
      'ЩС-2 Розетки',
      'Этаж 2, серверная',
      3,
      {
        shell_brand: 'Schneider',
        shell_code: 'Easy9',
        installation_method: 'Навесной',
        protection_degree: 'IP54',
        network_type: 'TN-C-S',
        power_supply_from: 'ВРУ-1',
        modules_count: 18,
        input_device_type: 'Автомат с УЗО',
        nominal_current: 40,
        trip_setting: 40,
        protection_characteristic: 'C',
        poles_count: 4,
        differential_current: 30,
        designation: 'QF2',
      },
      32,
    ),
    scheme(
      SCHEME_2A,
      PROJECT_2,
      'ВРУ-1',
      null,
      3,
      {
        shell_brand: 'IEK',
        installation_method: 'Напольный',
        protection_degree: 'IP31',
        network_type: 'TN-S',
        modules_count: 36,
        input_device_type: 'Автомат',
        nominal_current: 100,
        trip_setting: 100,
        protection_characteristic: 'D',
        poles_count: 4,
        designation: 'QF1',
      },
      21,
    ),
  ]

  const schemeLines: SchemeLineRow[] = [
    // ЩС-1 Освещение (5 линий)
    line(`${SCHEME_1A}-l1`, SCHEME_1A, 1, {
      circuit_breaker_designation: 'QF1.1',
      circuit_breaker_type: 'S201 C10',
      cb_nominal_current: 10,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 3×1.5',
      cable_length: 32,
      power_kw: 0.5,
      cos_phi: 0.95,
      phase_a_current: 2.39,
      load_name: 'Освещение коридор', load_type: 'LED',
    }),
    line(`${SCHEME_1A}-l2`, SCHEME_1A, 2, {
      circuit_breaker_designation: 'QF1.2',
      circuit_breaker_type: 'S201 C10',
      cb_nominal_current: 10,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 3×1.5',
      cable_length: 28,
      power_kw: 0.6,
      cos_phi: 0.95,
      phase_a_current: 2.87,
      load_name: 'Освещение open space', load_type: 'LED',
    }),
    line(`${SCHEME_1A}-l3`, SCHEME_1A, 3, {
      circuit_breaker_designation: 'QF1.3',
      circuit_breaker_type: 'S201 C10',
      cb_nominal_current: 10,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 3×1.5',
      cable_length: 24,
      power_kw: 0.4,
      cos_phi: 0.95,
      phase_a_current: 1.91,
      load_name: 'Освещение переговорная', load_type: 'LED',
    }),
    line(`${SCHEME_1A}-l4`, SCHEME_1A, 4, {
      circuit_breaker_designation: 'QF1.4',
      circuit_breaker_type: 'S201 C16',
      cb_nominal_current: 16,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 3×2.5',
      cable_length: 18,
      power_kw: 1.2,
      cos_phi: 0.92,
      phase_a_current: 5.93,
      load_name: 'Аварийное освещение', load_type: 'LED',
    }),
    line(`${SCHEME_1A}-l5`, SCHEME_1A, 5, {
      circuit_breaker_designation: 'QF1.5',
      circuit_breaker_type: 'S201 C10',
      cb_nominal_current: 10,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 3×1.5',
      cable_length: 14,
      power_kw: 0.3,
      cos_phi: 0.95,
      phase_a_current: 1.43,
      load_name: 'Освещение санузлов', load_type: 'LED',
    }),

    // ЩС-2 Розетки (4 линии, 3-фазная сеть)
    line(`${SCHEME_1B}-l1`, SCHEME_1B, 1, {
      circuit_breaker_designation: 'QF2.1',
      circuit_breaker_type: 'iC60N C16',
      cb_nominal_current: 16,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 3×2.5',
      cable_length: 22,
      power_kw: 2.5,
      cos_phi: 0.85,
      phase_a_current: 13.37,
      load_name: 'Розетки рабочих мест ряд 1', load_type: 'РБ',
    }),
    line(`${SCHEME_1B}-l2`, SCHEME_1B, 2, {
      circuit_breaker_designation: 'QF2.2',
      circuit_breaker_type: 'iC60N C16',
      cb_nominal_current: 16,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 3×2.5',
      cable_length: 20,
      power_kw: 2.5,
      cos_phi: 0.85,
      phase_b_current: 13.37,
      load_name: 'Розетки рабочих мест ряд 2', load_type: 'РБ',
    }),
    line(`${SCHEME_1B}-l3`, SCHEME_1B, 3, {
      circuit_breaker_designation: 'QF2.3',
      circuit_breaker_type: 'iC60N C16',
      cb_nominal_current: 16,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 3×2.5',
      cable_length: 26,
      power_kw: 2.5,
      cos_phi: 0.85,
      phase_c_current: 13.37,
      load_name: 'Розетки рабочих мест ряд 3', load_type: 'РБ',
    }),
    line(`${SCHEME_1B}-l4`, SCHEME_1B, 4, {
      circuit_breaker_designation: 'QF2.4',
      circuit_breaker_type: 'iC60N C25',
      cb_nominal_current: 25,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 5×4',
      cable_length: 12,
      power_kw: 5,
      cos_phi: 0.9,
      phase_a_current: 8.43,
      phase_b_current: 8.43,
      phase_c_current: 8.43,
      load_name: 'Серверная стойка (3 ф)', load_type: 'IT',
    }),

    // ВРУ-1 (3 линии, 3-фазная)
    line(`${SCHEME_2A}-l1`, SCHEME_2A, 1, {
      circuit_breaker_designation: 'QF1',
      circuit_breaker_type: 'NS100 D63',
      cb_nominal_current: 63,
      cb_protection_type: 'D',
      cable_brand: 'ВВГнг(А)-LS 5×16',
      cable_length: 8,
      power_kw: 30,
      cos_phi: 0.92,
      phase_a_current: 49.5,
      phase_b_current: 49.5,
      phase_c_current: 49.5,
      load_name: 'Холодильное оборудование', load_type: 'РБ',
    }),
    line(`${SCHEME_2A}-l2`, SCHEME_2A, 2, {
      circuit_breaker_designation: 'QF2',
      circuit_breaker_type: 'NS100 C40',
      cb_nominal_current: 40,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 5×6',
      cable_length: 14,
      power_kw: 15,
      cos_phi: 0.9,
      phase_a_current: 25.3,
      phase_b_current: 25.3,
      phase_c_current: 25.3,
      load_name: 'Освещение торгового зала', load_type: 'LED',
    }),
    line(`${SCHEME_2A}-l3`, SCHEME_2A, 3, {
      circuit_breaker_designation: 'QF3',
      circuit_breaker_type: 'iC60N C25',
      cb_nominal_current: 25,
      cb_protection_type: 'C',
      cable_brand: 'ВВГнг(А)-LS 5×4',
      cable_length: 18,
      power_kw: 8,
      cos_phi: 0.85,
      phase_a_current: 14.3,
      phase_b_current: 14.3,
      phase_c_current: 14.3,
      load_name: 'Кассовая зона', load_type: 'РБ',
    }),
  ]

  return { projects, schemes, schemeLines }
}
